import type { ThemeVariable, ThemeValues } from "../types/theme";

// Theme variable definitions (metadata only)
export const THEME_VARIABLES: ThemeVariable[] = [
  // Base Colors
  {
    name: "Background",
    cssVar: "--background",
    description: "Main background color",
    category: "color",
    group: "base",
  },
  {
    name: "Foreground",
    cssVar: "--foreground",
    description: "Main text color",
    category: "color",
    group: "base",
  },
  {
    name: "Muted Foreground",
    cssVar: "--muted-foreground",
    description: "Muted text",
    category: "color",
    group: "base",
  },
  {
    name: "Subtle Foreground",
    cssVar: "--subtle-foreground",
    description: "Subtle text",
    category: "color",
    group: "base",
  },

  // Surface Colors
  {
    name: "Card",
    cssVar: "--card",
    description: "Card backgrounds",
    category: "color",
    group: "surface",
  },
  {
    name: "Card Foreground",
    cssVar: "--card-foreground",
    description: "Text on cards",
    category: "color",
    group: "surface",
  },
  {
    name: "Popover",
    cssVar: "--popover",
    description: "Popover backgrounds",
    category: "color",
    group: "surface",
  },
  {
    name: "Popover Foreground",
    cssVar: "--popover-foreground",
    description: "Text on popovers",
    category: "color",
    group: "surface",
  },
  {
    name: "Muted",
    cssVar: "--muted",
    description: "Muted backgrounds",
    category: "color",
    group: "surface",
  },
  {
    name: "Accent",
    cssVar: "--accent",
    description: "Accent backgrounds",
    category: "color",
    group: "surface",
  },
  {
    name: "Accent Foreground",
    cssVar: "--accent-foreground",
    description: "Text on accent",
    category: "color",
    group: "surface",
  },

  // Brand Colors
  {
    name: "Primary",
    cssVar: "--primary",
    description: "Primary brand color",
    category: "color",
    group: "brand",
  },
  {
    name: "Primary Foreground",
    cssVar: "--primary-foreground",
    description: "Text on primary",
    category: "color",
    group: "brand",
  },
  {
    name: "Secondary",
    cssVar: "--secondary",
    description: "Secondary brand color",
    category: "color",
    group: "brand",
  },
  {
    name: "Secondary Foreground",
    cssVar: "--secondary-foreground",
    description: "Text on secondary",
    category: "color",
    group: "brand",
  },

  // State Colors
  {
    name: "Destructive",
    cssVar: "--destructive",
    description: "Destructive actions",
    category: "color",
    group: "state",
  },
  {
    name: "Destructive Foreground",
    cssVar: "--destructive-foreground",
    description: "Text on destructive",
    category: "color",
    group: "state",
  },
  {
    name: "Border",
    cssVar: "--border",
    description: "Border color",
    category: "color",
    group: "state",
  },
  {
    name: "Input",
    cssVar: "--input",
    description: "Input border color",
    category: "color",
    group: "state",
  },
  {
    name: "Ring",
    cssVar: "--ring",
    description: "Focus ring color",
    category: "color",
    group: "state",
  },

  // Chart Colors
  {
    name: "Chart 1",
    cssVar: "--chart-1",
    description: "Chart color 1",
    category: "color",
    group: "chart",
  },
  {
    name: "Chart 2",
    cssVar: "--chart-2",
    description: "Chart color 2",
    category: "color",
    group: "chart",
  },
  {
    name: "Chart 3",
    cssVar: "--chart-3",
    description: "Chart color 3",
    category: "color",
    group: "chart",
  },
  {
    name: "Chart 4",
    cssVar: "--chart-4",
    description: "Chart color 4",
    category: "color",
    group: "chart",
  },
  {
    name: "Chart 5",
    cssVar: "--chart-5",
    description: "Chart color 5",
    category: "color",
    group: "chart",
  },

  // Size
  {
    name: "Radius",
    cssVar: "--radius",
    description: "Border radius",
    category: "size",
    group: "base",
  },

  // Sidebar Colors
  {
    name: "Sidebar",
    cssVar: "--sidebar",
    description: "Sidebar background",
    category: "color",
    group: "sidebar",
  },
  {
    name: "Sidebar Foreground",
    cssVar: "--sidebar-foreground",
    description: "Sidebar text",
    category: "color",
    group: "sidebar",
  },
  {
    name: "Sidebar Primary",
    cssVar: "--sidebar-primary",
    description: "Sidebar primary",
    category: "color",
    group: "sidebar",
  },
  {
    name: "Sidebar Primary Foreground",
    cssVar: "--sidebar-primary-foreground",
    description: "Text on sidebar primary",
    category: "color",
    group: "sidebar",
  },
  {
    name: "Sidebar Accent",
    cssVar: "--sidebar-accent",
    description: "Sidebar accent",
    category: "color",
    group: "sidebar",
  },
  {
    name: "Sidebar Accent Foreground",
    cssVar: "--sidebar-accent-foreground",
    description: "Text on sidebar accent",
    category: "color",
    group: "sidebar",
  },
  {
    name: "Sidebar Border",
    cssVar: "--sidebar-border",
    description: "Sidebar border",
    category: "color",
    group: "sidebar",
  },
  {
    name: "Sidebar Ring",
    cssVar: "--sidebar-ring",
    description: "Sidebar focus ring",
    category: "color",
    group: "sidebar",
  },
];

// Light theme values
export const LIGHT_THEME: ThemeValues = {
  "--background": "#ffffff",
  "--foreground": "#2e3a5b",
  "--muted-foreground": "#58617c",
  "--subtle-foreground": "#777f94",
  "--card": "#ffffff",
  "--card-foreground": "#0a0a0a",
  "--popover": "#ffffff",
  "--popover-foreground": "#0a0a0a",
  "--primary": "#f37320",
  "--primary-foreground": "#fafafa",
  "--secondary": "#213f99",
  "--secondary-foreground": "#fafafa",
  "--muted": "#f5f5f5",
  "--accent": "#f5f5f5",
  "--accent-foreground": "#171717",
  "--destructive": "#e7000b",
  "--destructive-foreground": "#e7000b",
  "--border": "#e5e5e5",
  "--input": "#e5e5e5",
  "--ring": "#a1a1a1",
  "--chart-1": "#f54a00",
  "--chart-2": "#009689",
  "--chart-3": "#104e64",
  "--chart-4": "#ffba00",
  "--chart-5": "#fd9a00",
  "--radius": "0.625rem",
  "--sidebar": "#f1f5f9",
  "--sidebar-foreground": "#2e3a5b",
  "--sidebar-primary": "#171717",
  "--sidebar-primary-foreground": "#fafafa",
  "--sidebar-accent": "#f5f5f5",
  "--sidebar-accent-foreground": "#171717",
  "--sidebar-border": "#e5e5e5",
  "--sidebar-ring": "#a1a1a1",
};

// Dark theme values
export const DARK_THEME: ThemeValues = {
  "--background": "#303841",
  "--foreground": "#94a0ad",
  "--muted-foreground": "#eaebef",
  "--subtle-foreground": "#f5f5f7",
  "--card": "#36404a",
  "--card-foreground": "#94a0ad",
  "--popover": "#0a0a0a",
  "--popover-foreground": "#fafafa",
  "--primary": "#f37320",
  "--primary-foreground": "#fafafa",
  "--secondary": "#213f99",
  "--secondary-foreground": "#fafafa",
  "--muted": "#262626",
  "--accent": "#262626",
  "--accent-foreground": "#fafafa",
  "--destructive": "#82181a",
  "--destructive-foreground": "#fb2c36",
  "--border": "#262626",
  "--input": "#262626",
  "--ring": "#737373",
  "--chart-1": "#1447e6",
  "--chart-2": "#00bc7d",
  "--chart-3": "#fd9a00",
  "--chart-4": "#ad46ff",
  "--chart-5": "#ff2056",
  "--radius": "0.625rem",
  "--sidebar": "#37424c",
  "--sidebar-foreground": "#94a0ad",
  "--sidebar-primary": "#1447e6",
  "--sidebar-primary-foreground": "#fafafa",
  "--sidebar-accent": "#262626",
  "--sidebar-accent-foreground": "#fafafa",
  "--sidebar-border": "#262626",
  "--sidebar-ring": "#525252",
};

// Helper function to merge theme variables with values
export const getThemeWithValues = (themeValues: ThemeValues) => {
  return THEME_VARIABLES.map((variable) => ({
    ...variable,
    value: themeValues[variable.cssVar] || "",
  }));
};
