import {
  Root,
  Portal,
  Spotlight,
  SpotlightRing,
  Step,
  Arrow,
  Header,
  Title,
  Description,
  Close,
  Prev,
  Next,
  Skip,
  StepCounter,
  Footer,
  //
  TourPortal,
  TourSpotlight,
  TourSpotlightRing,
  TourStep,
  TourArrow,
  TourHeader,
  TourTitle,
  TourDescription,
  TourClose,
  TourPrev,
  TourNext,
  TourSkip,
  TourStepCounter,
  TourFooter,
  //
  type TourProps,
} from "./Tour";
import { TourWrapper, type TourWrapperProps, type TourStep as TourStepType, type ButtonConfig } from "./TourWrapper";

const Tour = Object.assign(TourWrapper, {
  Root,
  Portal,
  Spotlight,
  SpotlightRing,
  Step,
  Arrow,
  Header,
  Title,
  Description,
  Close,
  Prev,
  Next,
  Skip,
  StepCounter,
  Footer,
  //
  TourPortal,
  TourSpotlight,
  TourSpotlightRing,
  TourStep,
  TourArrow,
  TourHeader,
  TourTitle,
  TourDescription,
  TourClose,
  TourPrev,
  TourNext,
  TourSkip,
  TourStepCounter,
  TourFooter,
});

export { Tour };
export type { TourProps, TourWrapperProps, TourStepType as TourStep, ButtonConfig };
